# park_list = ['Auburn Narrows Natural Area',
#  'Bassett Pond Natural Area',
#  'Big Bend and Landsburg Natural Areas',
#  'Big Finn Hill Park',
#  'Bingaman Pond Natural Area',
#  'Black Diamond Open Space',
#  'Boulevard Lane Park',
#  'Boxley Creek Site',
#  'Bridle Crest Trail Site',
#  'Bryn Mawr Park',
#  'Burke Gilman Trail Site',
#  'Camelot Park',
#  'Canyon Creek Natural Area',
#  'Carnation Marsh Natural Area',
#  'Cavanaugh Pond',
#  'Cecil Moses Memorial Park',
#  'Cedar Downs Site',
#  'Cedar Grove Road Natural Area',
#  'Cedar River to Lake Sammamish Trail Site',
#  'Cedar River Trail Site',
#  'Chinook Bend Natural Area',
#  'Coalfield Park',
#  'Cold Creek Natural Area',
#  'Cottage Lake Park',
#  'Cougar Mountain Regional Wildland Park',
#  'Cougar/Squak Corridor',
#  'Covington Natural Area',
#  'Danville-Georgetown',
#  'Dick Thurnau Memorial Park',
#  'Dockton Beach Park',
#  'Dockton Forest',
#  'Dockton Natural Area',
#  'Duthie Hill Park',
#  'Duvall Park',
#  'East Lake Sammamish Trail Site',
#  'East Plateau Trail Site',
#  'Ellis Creek Natural',
#  'Evans Creek Natural Area',
#  'Evans Crest Natural Area',
#  'Fall City',
#  'Fall City Natural Area',
#  'Fall City Park West',
#  'Five Mile Lake Park',
#  'Flaming Geyser Natural Area',
#  'Foothills Trail Site',
#  'Fred V. Habenicht Rotary Park',
#  'Gold Creek Park',
#  'Grand Ridge Park',
#  'Green River Natural Area',
#  'Green River Trail Site',
#  'Green To Cedar Rivers Trail Site',
#  'Griffin Creek Natural Area',
#  'Hatchery Natural Area',
#  'Horsehead Bend Natural Area',
#  'Hyde Lake Park',
#  'Inspiration Point Natural Area',
#  'Instebo Park',
#  'Island Center Forest',
#  'Issaquah Creek',
#  'Issaquah Preston Trail Site',
#  'Juanita Triangle Park',
#  'Juanita Woodlands Park',
#  'Kathryn C. Lewis',
#  'Kathryn Taylor Equestrian Park',
#  'Kentlake Athletic Fields',
#  'Kingsgate Park',
#  'Klahanie Trail Site',
#  'Lake Francis Park',
#  'Lake Geneva Park',
#  'Lake Joy Park',
#  'Lake Youngs Park',
#  'Lake Youngs Trail Site',
#  'Landsburg Kanaskat Trail Site',
#  'Landsburg Trailhead',
#  'Levdansky Park',
#  'Log Cabin Reach Natural Area',
#  'Lower Bear Creek Natural Area',
#  'Lower Newaukum Creek Natural Area',
#  'Manzanita Natural Area',
#  'Maple Valley Heights Park',
#  'Maplewood Heights Park',
#  'Maplewood Park',
#  'Marjorie R. Stanley Natural Area',
#  'Marymoor Park',
#  'Marymoor Bellevue Ballfield Complex',
#  'Maury Island Natural Area',
#  'Maury Island Marine Park',
#  'May Creek Park - County',
#  'May Valley Park',
#  'McGarvey Park Open Space',
#  'Meridian Jr. High School',
#  'Middle Bear Creek Natural Area',
#  'Middle Fork Snoqualmie Natural Area',
#  'Middle Issaquah Creek Natural Area',
#  'Mirrormont Park',
#  'Mitchell Hill Connector Forest',
#  'Moss Lake Natural Area',
#  'Mouth Of Taylor Reach Natural Area',
#  'Mullen Slough Natural Area',
#  'Neill Point Natural Area',
#  'North Green River Park',
#  'Northilla Beach Natural Area',
#  'North Meridian Park',
#  'Northshore Athletic Fields',
#  'North Shorewood Park',
#  'Novelty Hill Little League Fields',
#  'Paradise Lake Natural Area',
#  'Paradise Valley Natural Area',
#  'Park Orchard Park',
#  'Patterson Creek Natural Area',
#  'Peterson Lake Natural Area',
#  'Petrovitsky Park',
#  'Piner Point Natural Area',
#  'Pinnacle Peak Park',
#  'Pipeline Number 5 Trail Site',
#  'Preston Athletic Fields',
#  'Preston Mill',
#  'Preston Park',
#  'Preston Ridge Park',
#  'Preston Snoqualmie Trail Site',
#  'PSE Trail Site',
#  'Quigley Park',
#  'Raabs Lagoon Natural Area',
#  'Raging River Natural Area',
#  'Rattlesnake Mountain Scenic Area',
#  'Ravenhill Open Space',
#  'Ravensdale Park',
#  'Ravensdale Retreat Natural Area',
#  'Redmond Ridge Park',
#  'Redmond Ridge Trail Site',
#  'Redmond Watershed Addition Park',
#  'Redmond Watershed Trail Site',
#  'Renton Park',
#  'Ring Hill Forest',
#  'Sammamish River Trail Site',
#  'Shinglemill Creek Natural Area',
#  'Sierra Heights Park',
#  'Sixty Acres Park',
#  'Skyway Park',
#  'Snoqualmie Valley Trail Site',
#  'Soaring Eagle Regional Park',
#  'Soos Creek 140th Open Space',
#  'Soos Creek Park and Trail',
#  'Soos Creek To Lake Youngs Trail Site',
#  'South County Ballfields',
#  'Spring Lake/Lake Desire Park',
#  'Squak Mt/Tiger Mt Corridor',
#  'Steve Cox Memorial Park',
#  'Stillwater Natural Area',
#  'Sugarloaf Mountain Forest',
#  'Tanner Landing Park',
#  'Taylor Mountain Forest',
#  'Three Forks Natural Area',
#  'Tollgate Farm',
#  'Tolt River - John MacDonald Park',
#  'Tolt Pipeline Trail Site',
#  'Upper Bear Creek Natural Area',
#  'West Sammamish Trail Site',
#  'Wetland 14 Natural Area',
#  'White Center Heights Park',
#  'White Center Pond Natural Area',
#  'Whitney Bridge Park',
#  'Weyerhaeuser King County Aquatic Center',
#  'Klondike Gold Rush National Historical Park',
#  ]
top_parks = [
    'Discovery Park',
    'Olympic Sculpture Park',
    'Green Lake Park',
    'Carkeek Park',
    'Washiton Park Arboretum',
    'Gas Works Park',
    'Seward Park',
    'Kubota Garden',
    'Kerry Park',
    'Magnuson Park',
    'Volunteer Park',
    'Viretta Park',
]

top_beaches = [
    'Alki',
    'Golden Gardens',
    'Denny Blaine',
    'Carkeet Park',
    'Green Lake Park',
    'Madison Park',
    'Matthews Beach',
    'Andover Place'
]

top_cafes = [
    'La Marzocco',
    'Analog',
    'Mr.West Cafe Bar',
    'Slate',
    'Seattle Coffee Works',
    'Elm Coffee Roasters',
    'Preserve and Gather',
    'Poindexter Coffee',
    "Caffe D'arte",
    'Makeda and Mingus'
]